### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by hosseinmasoodi** [Star-Academy/Summer1401-Project-Team02#6]
## Upload File process notes:
- [x] splitting data by `,` in csv files will cause error for sentence-including datasets
- [ ] filename problem while importing data to database table
- [x] redundant logging through process
- [x] basic refactoring
- [x] CSV columns data types are ignored
- [ ] complex Json would cause error.

## Preview
- [x] what should we do if the client request the preview some node that has more than one previous node?
- [x] how can we handle exception when the client requests the preview of source node?

## ideas we can think about:
- [x] separate all query strings from nodes and store them in a constant file. (using string.format feature)

## Tasks to do:
* **Testing Upload process**:
   - [ ]  import a huge file size
   - [ ] filename contain special characters like `.`, `white space` and ...
   - [ ] long file name (truncate or not)
   - [ ] ? overwriting tables
   - [ ] ? files with similar names
   - [ ] complex Json files (non existing data types: default switch case)
   - [ ] handle expected exceptions and return reasonable messages
* **Testing Add destination process**:
   - [ ] similar names
   - [ ] long names
   - [ ] ? overwrite tables
   - [ ] handle expected exceptions and return reasonable messages 
* **Testing Download process**:
   - [ ] download non existing table -> appropriate message
   - [ ] download table with special names

* **Initialize method performance**: reduce the time complexity by setting only the necessary nodes' headers.
* **table name hashing and working with id**
* **Pipeline inventory**:
   - [ ] add/remove pipeline
   - [ ] save and update
   - [ ] reload all pipelines
   - [ ] get a pipeline by name (hash also)
* **Nodes**:
   - [ ] aggregate functions
   - [ ] filter
   - [ ] string manipulation
   - [ ] join 
* **log more precisely**
* **overwriting in columns or adding a new column**
* **handling new names in split node**
* **using enum for file formats in download and upload**
* **Adding sql connection feature for uploading and downloading (rethink on the current structure)**
